server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  application:
    name: students-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0